name: 'DeployAction'
description: 'Deploying terraform modules'
author: 'SolidifyDemo'

runs:
  using: "composite"
  steps:
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4.0.0
      with:
        tflint_wrapper: true
      
    - name: Lint
      shell: bash
      run: | 
        tflint --version
        tflint --init
        tflint -f compact
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Validate
      shell: bash
      run: terraform validate
