name: 'DeployAction'
description: 'Deploying terraform modules'
author: 'SolidifyDemo'
inputs:
  access-token:
    description: "Some secret value"
    required: true

runs:
  using: "composite"
  steps:
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4.0.0
      with:
        tflint_wrapper: true
      
    - name: Lint
      shell: bash
      run: | 
        tflint --version
        tflint --init
        tflint -f compact
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Set up Git authentication
      shell: bash
      run: |
        git config --global url."https://${{ inputs.access-token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      

    - name: Init
      shell: bash
      run: terraform init

    - name: Validate
      shell: bash
      run: terraform validate
